<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product</name>
   <tag></tag>
   <elementGuidId>f1052df8-f786-4f92-8eb2-c467959675f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;queryItemPageForm&quot;]/div[2]/div[1]/div[1]/div[1]/a/h3</value>
   </webElementProperties>
</WebElementEntity>
